### PR TITLE
Add synthetic spectra for large spectrum type

### PR DESCRIPTION
**Pull request by TranHuuNhatHuy**
This pull request is to address #1 which:
1. Prepares a [synthetic spectrum generator](https://github.com/TranHuuNhatHuy/RADIS-Spectrum-Fitting-Benchmark/commit/343697a6bc16a27e9d713b6b440933986d499caf).
2. Add [several synthetic large spectra](https://github.com/TranHuuNhatHuy/RADIS-Spectrum-Fitting-Benchmark/commit/2a6e908955260702fc5968dd392f6c5594d73403) which are generated under different conditions. More of them will be added during the second week of dealing with large spectra according to the [project timeline](https://github.com/radis/radis/wiki/GSOC-2022-Application-RADIS-Tran-Huu-Nhat-Huy:-Spectrum-Fitting-Improvement#week-2---3-jun-20---jul-3).
3. Add [some empty models](https://github.com/TranHuuNhatHuy/RADIS-Spectrum-Fitting-Benchmark/commit/d904b2aa32e1e81fedcabdfe7deedb9312eb3138) which will be heavily modified during benchmarking processes of corresponding spectrum types.

### 1. Synthetic large spectra and JSON
A unified JSON structure will be used throughout the benchmarking process to store and load spectrum fitting conditions. If possible, I would like to implement this structure to new fitting function for RADIS, **so that in the future RADIS users can simply add their spectrum file (.spec) and state the parameters/conditions in a formatted JSON file**.
In particular, the file name used for both the spectrum files and JSON files will be like this:
```python
"synth-{molecule}-{isotope}-{from_wl}-{to_wl}-{wunit}-{pressure}-t{Tgas}-v{Tvib}-r{Trot}-p{path_length}-sl{slit}{slit_unit}"
```
and the JSON structure for stating the ground-truth will be like this, for example:
```JSON
{
  "fileName": "CO2-1-1900-2300-cm-1.01325-t300-v300-r300-p1-sl0.5nm.spec",
  "molecule": "CO2",
  "isotope": "1",
  "from_wavelength": 1900,
  "to_wavelength": 2300,
  "pressure": 1.01325,
  "mole_fraction": 0.1,
  "path_length": 1,
  "slit": "0.5 nm",
  "fit": {
    "Tgas": 300,
    "Tvib": 300,
    "Trot": 300,
  }
}
```
This means there are 3 fit parameters: `Tgas`, `Tvib` and `Trot` with their corresponding initial values. 
About the generator, firstly it will read the initial conditions (stated manually by me, for now), then it generates a spectrum from those conditions. To make it look like an experimental one, noises will be added with scale at 1% of max radiance value. Finally, the noise-added spectrum will be save as `.spec` file and its information will be stored as formatted JSON structure. These files will later be used for benchmarking process to test multiple fitting pipelines, and more files will definitely be added later.

### 2. Several synthetic spectra for large type
Added. Some of them are inspired from atmospheric components of several planets in Sol System, including Terra.

### 3. Empty model files
Now just empty. In the end they will contain the best pipeline of each spectrum type.

### CODE REVIEW

**Comment by TranHuuNhatHuy** [comment]
Dear mentors @erwanp , @anandxkumar , @gagan-aryan , and @minouHub ,

According to your suggestions, in the latest commit I have added extra features into the generation of synthetic spectra, which in summary:
- 1.4 nm slit, which is adjustable through JSON.
- -0.2 nm cutoff.
- Gaussian noise globally, with scale around 0.5% of max radiance: 
```python
s_wav, s_val = s.get('radiance')
noise_scale = max([val for val in s_val if not(math.isnan(val))]) * 0.005 # Prevent NaN
s_val += np.random.normal(size = s_val.size, scale = noise_scale)
```
- Dilatation with scale 0.66% of deviation
```python
wav_mean = np.mean([wav for wav in s_wav if not(math.isnan(wav))])
s_wav = wav_mean + (s_wav - wav_mean) * 1.0066
```

So the generated synthetic spectrum is gonna be like this:

image

While its calculated-from-ground-truth counterpath is:

image

What do you think about this? Does it look "high-quality fake" enough? If deemed acceptable, I will merge this PR into main branch.

**Comment by anandxkumar** [comment]
@TranHuuNhatHuy great work! The idea of using a JSON format for storing the spectrum information seems convenient to me for modifying the parameters.  The approach you used to create the synthetic spectrum looks promising but I will leave that part to @erwanp to decide to make sure we aren't breaking any physics :)

**Comment by erwanp** [comment]
Hello, can you plot both spectra on same graph ? Except from that, looks all good --> go ahead

**Comment by TranHuuNhatHuy** [comment]
Thank you Mr. @erwanp and @anandxkumar for your comments.

Here I got difference result between two spectra. As you can see, the synth spectrum features both noise and dilatation effects.

image

I will merge this into `main` branch and start the benchmarking process right now.

**Pull request merged**
